---
title: "Kombinatorika"
---


## Uvod

Za početak ćemo objasniti osnovne metode prebrojavanja. Prvo uvedimo oznaku: $$n!=n(n-1)(n-2)\cdot \cdots \cdot 2 \cdot 1, \ \text{za } n\in \mathbb{N}$$ Ovo čitamo \textbf{$n$ faktorijela}. Definiramo $0!=1$.

Neka je $X$ $n$-člani skup. Tada definiramo:

- permutacija --- uređena $n$-torka skupa $X$ 
- kombinacija --- $n$-člani podskup skupa $X$

Primijetimo da možemo jednostavnije reći da je kod permutacija poredak bitan (primjerice slaganje ljudi u red), a kod kombinacija nije (na primjer biranje dviju kugli sladoleda).

::::{.primjer}

Neka je $X$ $n$-člani skup. Na koliko načina možemo odabrati uređenu $k$-torku elemenata skupa $X$ 

(a) uz dopuštena ponavljanja?
(b) bez ponovljenih elemenata?

:::{.rjesenje-primjera}

Označimo traženu $k$-torku s $(x_1,...,x_n)$.

(a) Svaki element $x_k$ možemo odabrati na $n$ načina pa dobivamo $$\underbrace{n\cdot\cdots\cdot n}_{k \ \text{puta}}=n^k$$
(b) Za $x_1$ imamo $n$ elemenata za odabir, zatim za $x_2$ preostalih $n-1$ elemenata, i tako dalje do $n-k+1$ izbora za $x_k$. Imamo $$n(n-1)\cdots(n-k+1)=\frac{n!}{(n-k)!}$$
:::
::::

:::{.primjer}
Neka je $X$ $n$-člani skup. Na koliko načina možemo odabrati $k$-člani podskup skupa $X$ 

(a) uz dopuštena ponavljanja?
(b) bez ponovljenih elemenata?
:::
Ovaj primjer ipak nije lako intuitivno riješiti pa ćemo u idućem teoremu priložiti tablicu radi jednostavnijeg prikaza. Uvedimo oznaku \textbf{binomnog koeficijenta}: $$\binom{n}{k} = \frac{n!}{k!(n-k)!}$$ 

:::{.teorem}
*Broj odabira $k$ objekata iz $n$-članog skupa $X$ prikazan je u tablici:*

| | redoslijed bitan| redoslijed nebitan |
|:----:+:-----:+:------:|
| **ponavljanje dopušteno** | $\displaystyle n^k$ | $\displaystyle \binom{n+k-1}{n-1}$ |
| **ponavljanje nije dopušteno** | $\displaystyle \frac{n!}{(n-k)!}$ | $\displaystyle \binom{n}{k}$ |
:::

Treba zapamtiti da $\binom{n}{k}$ označava broj $k$-članih podskupova $n$-članog skupa. Lakše rečeno, od $n$ ljudi biramo njih $k$ (jasno je da je to kombinacija bez ponavljanja).

::::{.primjer}
U trgovini postoje tri vrste soka: sok od jabuke, sok od breskve i sok od naranče. Roko treba kupiti pet sokova. Na koliko načina može obaviti kupnju 

(a) bez dodatnih uvjeta?
(b) ako ne smije kupiti više od jednog soka od jabuke?

:::{.rjesenje-primjera}

(a) Očito se radi o kombinaciji s ponavljanjem pa samo uvrstimo u potrebnu formulu: $$n=3,\ k=5 \quad \Longrightarrow \quad \displaystyle\binom{n+k-1}{n-1}=\binom{3+5-1}{3-1}=\binom{7}{2}=21$$
    
(b) Po pravilu sume promatrat ćemo dva slučaja --- kupljen je jedan sok od jabuke te nije kupljen ni jedan sok od jabuke --- a zatim ćemo zbrojiti broj pojednih slučajeva. Ako je kupljen jedan sok od jabuke, preostaju samo dvije vrste soka za birati $(n=2)$ od kojih uzimamo četiri soka $(k=4)$: $$\displaystyle\binom{n+k-1}{n-1}=\binom{2+4-1}{2-1}=\binom{5}{1}=5$$ Ako ne kupuje sok od jabuke, potrebno je odabrati pet sokova $(k=5)$ od preostala dva ponuđena $(n=2)$: $$\displaystyle\binom{n+k-1}{n-1}=\binom{2+5-1}{2-1}=\binom{6}{1}=6$$ Sada vidimo da Roko može kupiti sokove na ukupno $11$ načina.

:::
::::

## Zadatci

:::{.zadatak}
Ante, Maša, Stjepan i Željka idu u kino. Na koliko načina mogu sjediti u kinu

(a) bez dodatnih uvjeta?

(b) tako da Ante i Stjepan uvijek sjede jedan pored drugoga? 

Pretpostavljamo da svi sjede zajedno, na uzastopna četiri mjesta.
:::

:::{.rjesenje}
<details>
<summary> Prikaži rješenje </summary>
(a) Samo ih trebamo permutirati pa je rješenje $4!=24$.

(b) Ako Ante i Stjepan sjede zajedno, tada ih možemo promatrati kao blok pa imamo ukupno tri objekta (blok Ante Stjepan, Maša, Željka) za permutirati što daje $3!=6$ načina. Sada je još potrebno pomnožiti s $2$ jer Ante i Stjepan unutar svog bloka mogu sjediti na dva načina pa je konačno rješenje $12$.

</details>
:::


---

:::{.zadatak}
U restoranu se za ručak nude 3 vrste juhe, 5 glavnih jela, 4 deserta. Koliko različitih ručkova može naručiti gost ako:

(a) bira točno jednu juhu, jedno glavno jelo i jedan desert?
(b) bira glavno jelo i desert, ali juhu uzima samo ako želi?

:::

:::{.rjesenje collapse="true"}
<details>
<summary> Prikaži rješenje </summary>
(a) Po principu produkta imamo ukupno $3\cdot 5\cdot 4=60$ ručkova.
(b) Glavno jelo i desert gost bira na $5\cdot 4=20$ načina. Juhu ne mora, ali može uzeti. To nam daje ukupno četiri opcije za juhu, jedna od triju juha ili ni jedna. Ukupno $20\cdot 4=80$ ručkova.
</details>

:::

---

:::{.zadatak}
Na koliko načina $n$ ljudi može sjesti za okrugli stol?
:::

:::{.rjesenje}
<details>
<summary> Prikaži rješenje </summary>

Riješit ćemo na dva načina.

(i) Smjestimo odmah sve ljude za okrugli stol. To možemo napraviti na $n!$ načina jer za prvu osobu imamo $n$ mjesta, za drugu $n-1$ itd. Ali primijetimo da su neki od tih rasporeda jednaki jer rotacijom jednog razmještaja dobijemo novi, ali realno se nije ništa promijenilo. Stoga moramo podijeliti s $n$ jer je moguće napraviti ukupno $n$ rotacija. Ukupno rasporeda ima $(n-1)!$. 

(ii) Prvo fiksiramo jednu osobu. Sada je ostalo $n-1$ slobodnih mjesta pa na njih smjestimo ostale osobe. Tada imamo ukupno $(n-1)!$ rasporeda.

</details>
:::

---

:::{.zadatak}
(*Dirichletov princip*) Ako imamo 13 ljudi u skupini, dokažite da tada barem dvije osobe imaju rođendan istoga mjeseca.
:::

:::{.rjesenje}
<details>
<summary> Prikaži rješenje </summary>

Prilično je intuitivan rezultat, a dokazat ćemo ga tako što ćemo pretpostaviti suprotno --- ne postoje dvije osobe koje imaju rođendan istog mjeseca. Bez smanjenja općenitosti neka prva osoba ima rođendan u siječnju, druga u veljači, i tako do dvanaeste osobe koja ima rođendan u prosincu. Trinaesta osoba nema svoj trinaesti mjesec pa mora imati rođendan u jednom od prethodnih mjeseci što je u kontradikciji s pretpostavkom. Time je tvrdnja dokazana. 

</details>
:::

---

:::{.zadatak}
Dokažite da u grupi od $n\geq 2$ ljudi postoje dvije osobe koje poznaju isti broj ljudi. Pretpostavljamo da su poznanstva obostrana, tj. ako osoba A poznaje osobu B, tada i B poznaje A.
:::

:::{.rjesenje}
<details>
<summary> Prikaži rješenje </summary>

Kao u prethodnom zadatku, numerirajmo osobe i pretpostavimo da sve osobe poznaju različit broj ljudi. Tada prva osoba nema poznanika, druga ima jednog, a $n$-ta onda ima $n-1$ poznanika. Ali to znači da $n$-ta osoba poznaje prvu, ali prva ne poznaje nitko. To je u kontradikciji s pretpostavkom da su poznanstva obostrana pa ne vrijedi ni da svi imaju različit broj poznanika. Tako je tvrdnja dokazana.

</details>
:::